name: Nodejs-poc-for-cache

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        version: [16, 18, 20]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Upload coverage report
      if: success()
      uses: codecov/codecov-action@v3
      with:
        files: './coverage/*.json'
